version: '3.8'

services:

  db:
    image: mariadb:10.5
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: QT6e5APtSYaU
      MYSQL_USER: root
      MYSQL_PASSWORD: QT6e5APtSYaU
      MYSQL_DATABASE: synacvtcci_db
    volumes:
      - ./db:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 83:80
    environment:
      UPLOAD_LIMIT: 300M

  app:
    container_name: app
    restart: always
    build:
      context: ./docker
    depends_on:
      - db
    environment:
      - APP_ENV=prod
      - XDEBUG_MODES=off
      - TZ=Africa/Abidjan
      - DATABASE_URL=mysql://root:QT6e5APtSYaU@db:3306/synacvtcci_db?serverVersion=14
    volumes:
      - ./app:/var/www/html

  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - app
    ports:
      - 82:80
