version: '3.8'

networks:
  fenapalci:

services:

  db:
    image: mariadb:10.5
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: QT6e5APtSYaU
      MYSQL_USER: root
      MYSQL_PASSWORD: QT6e5APtSYaU
      MYSQL_DATABASE: fenapalci_db
    volumes:
      - ./db:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - 3306:3306
    networks:
      - fenapalci

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 15432:80
    environment:
      UPLOAD_LIMIT: 300M
    networks:
      - fenapalci

  app:
    container_name: app
    restart: always
    build:
      context: ./docker
    environment:
      - APP_ENV=prod
      - DATABASE_URL=mysql://root:QT6e5APtSYaU@db:3306/fenapalci_db?serverVersion=14
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html
    networks:
      - fenapalci

  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - app
    ports:
      - 85:80
    networks:
      - fenapalci
